name = "lucabertelli-consulting"
compatibility_date = "2024-09-23"

[[kv_namespaces]]
binding = "lb_consulting"
id = "01ee33bd3673427c975a9804434376d6"

[env.preview]
name = "lucabertelli-consulting-preview"
